### PR TITLE
Landing Page

### PR DESCRIPTION
**Pull request by ryscheng**
@willscott Wanna give some comments?
The manifesto is more of a brain dump than cohesive thinking, so please feel free to suggest changes.

### CODE REVIEW

**Comment by willscott** [comment]
The third-party stuff here makes this change so big that github won't
display it :(

**Comment by ryscheng** [comment]
Haha yea. Sorry about that. I'd recommend looking at the branch directly,
since there's really no relevant diff.

https://github.com/ryscheng/radiatus.io-static/blob/ryscheng-new/index.html

All the content is in index.html

**Comment by willscott** [comment]
Awesome!

comments:
- What's with the trees? they're a bit stock-image-y for my tastes.
- chrome tells me the file 'css/no.png' is missing.
- should 'decentralized' flip with 'federated'?  should 'in the cloud' flip with 'on your desktop'?
- Consider also citing "we, the web kids" (http://pastebin.com/0xXV8k7k)
- The developer 'make money' pitch is weak. How would the developer make money? I can imagine 'sell premium features', and charge for services, in addition to an app store.
- Also have some type-edit nits, I can make those in the repo when you give me the go ahead.

**Comment by ryscheng** [comment]
- Lol the pic of the trees was actually added by me. It was the nicest picture of Radiatus clouds that I could find. See the stripes???? haha I can change it when I find a better picture. Found this website which is pretty cool if you want to peruse https://unsplash.com/
- Fixed missing no.png
- Done. Not sure what you mean by "on your desktop". I believe the most common use case will be helping users setup VMs on a IaaS cloud provider.
- Wanna take a stab at adding that? Not sure where to put it
- I see what you mean. It's not a major selling point, but I do want to reassure developers that we will be friendly to certain business models. Can you give it a go?
- Edit away, please :)

**Pull request merged**
